services:
  app:
    build: .
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_SERVICE=app
      - DD_ENV=${ENVIROMENT}
    networks:
      - datadog-agent-monitoring
    ports:
      - "8080:8080"
    env_file:
      - .env.development

networks:
  datadog-agent-monitoring:
    external: true